CORE
Thrower
--function Thrower.test --assert-no-exceptions-thrown --throw-runtime-exceptions
line 39 assertion at file Thrower.java line 39 .*: FAILURE
line 42 assertion at file Thrower.java line 42 .*: FAILURE
line 45 assertion at file Thrower.java line 45 .*: FAILURE
line 48 assertion at file Thrower.java line 48 .*: FAILURE
line 51 assertion at file Thrower.java line 51 .*: FAILURE
^EXIT=10$
^SIGNAL=0$
--
--
Checks that the runtime exceptions still throw with `--throw-runtime-exceptions`
even when `--assert-no-exceptions-thrown` is specified.
